apiVersion: v1
kind: Service
metadata:
  name: pxbackup-${VERSIONS_TAG}
  namespace: pxdocs-backup
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: pxbackup-${VERSIONS_TAG}